# .github/workflows/ci.yml

name: Continuous Integration
permissions:
  contents: read

# This workflow runs on every push or pull request to the 'main' branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checks out your repository's code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Sets up the Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # Step 3: Installs project dependencies securely
      - name: Install dependencies
        run: npm ci

      # Step 4: Runs the linter to check for code style issues
      - name: Run linter
        run: npm run lint

      # Step 5: Runs the build command to ensure the project compiles
      - name: Build project
        run: npm run build